### ISSUE TITLE
Package causes constant reloads

### ISSUE THREAD

**Issue by StorytellerCZ** [jamauro/offline#19]
Recently tested out a branch in my project and the package causes constant reloads:

https://github.com/user-attachments/assets/0a7505de-c275-462a-9684-8b89d79dd3d1

Removing the package ends the reloads. Clearing IndexedDB does fix the issue as well.

I'm wondering if this is due to some issue between versions or specific to HMR in development.

Either way wanted to let you know and everyone else how to fix this.

**Comment by jamauro** [comment]
Thanks for reporting. I will try to repro. If you can isolate with some specific repro steps, that would really help diagnose. It's entirely possible that this only happens with HMR. 

I suggest starting from a clean slate to see if you can repro reliably.

**Comment by jamauro** [comment]
I was able to repro this when flipping between the tests for the package and running my app. There was some stale data in the `syncs` indexeddb object store. This should be fixed in `v0.3.1`.

**Comment by StorytellerCZ** [comment]
Thanks a lot!

**Comment by wildhart** [comment]
I'm still getting infinite reloads with `v0.3.1`.  I'm upgrading from `v0.2.3` on my project.  Running with 0.2.3 is fine, then `meteor add jam:offline@0.3.1` and re-start causes an infinite reload.

![image](https://github.com/user-attachments/assets/fbfd3d45-3153-4eb7-bfaf-22ac51680213)

Downgrading to 0.2.3 or clearing all site data fixes the reload.

**Comment by StorytellerCZ** [comment]
Can confirm this again. I have added MontiAPM and after HMR the page started re-loading non-stop. Also got reports from some customers with the same problem.

**Comment by jamauro** [comment]
Thanks for reporting. If y'all could help with a minimal repro, I'd really appreciate it. 

One other thing that could help diagnose: use the package locally in your `packages` folder, console log the `keepErrors` and comment out the `window.reload` inside here: https://github.com/jamauro/offline/blob/9cb6c4c49bdd2ba6307d507883bc20f4259ec7f0/lib/config.js#L23

and share the errors you see.

**Comment by StorytellerCZ** [comment]
Will try to use locally when I get on a train later today.

**Comment by StorytellerCZ** [comment]
Got this:
![image](https://github.com/user-attachments/assets/038a92e5-52b1-4123-95a9-1736eb5f99a7)

The condition to trigger this was that the user had to be logged in.

**Comment by jamauro** [comment]
Thanks. Still not entirely sure what the root cause is. I was hoping that console logging `keepErrors` might provide some clues. But I will add some better error handling for the `clear` function.

**Comment by StorytellerCZ** [comment]
I think I found the issue. PR incoming.

**Comment by jamauro** [comment]
I just published `v0.3.2` that improves error handling and removes automatic reloading of the window. Curious to hear how it goes for y'all and if you continue seeing errors in the browser console when syncing. Please share if you do so we can rule out any issues with this package and possibly reintroduce automatic reload if it makes sense.
